### PR TITLE
Added native support for UnityJigglePhysics.

### PR DESCRIPTION
**Pull request by naelstrof**
Allows creators to freely use JiggleRigBuilder on their models to get jiggle effects.

Tried to make the pull request as clean as possible. I did the following in this pull request:

* Packed UnityJigglePhysics into the unitypackage next to the ModelReplacementAPI assembly definition.
* Included a submodule for a branch of UnityJigglePhysics that's specifically designed to work with BepinEx to include in the ModelReplacementAPI.dll. (bcompat)
* Updated the ModelReplacementAPI.dll with a fresh build. **I have disabled the TooManyEmotes code in this build as I didn't have access to the modified TooManyEmotes_publicized.dll, and didn't know how to generate it.**

Further improvements like adding overriding LOD settings would come in a new pull request.

### CODE REVIEW

**Comment by naelstrof** [comment]
Oh uh, I think I might've accidentally packed a prefab called CreatureA into the unitypackage. Sorry!

**Comment by BunyaPineTree** [comment]
That's alright, I need to make a separate repository for the unity project anyways to prevent silly things like this. 
I had a question on what you meant by LOD settings. Is it LOD settings inherent in jigglePhysics? Or are you referring to the base game LODs.

**Comment by naelstrof** [comment]
By "LOD settings" I was referring to how Dynamic Bones has a distance disable feature, UnityJigglePhysics has a similar feature but it's done through shared JiggleRigLOD scriptable objects.

Through script you can set them to adjust how performant they are, just as you have with your DynamicBone. It shouldn't be super necessary since I can't imagine 4 avatars needing 400+ jigglebones... right? 😔

**Comment by naelstrof** [comment]
Oh yeah and let me know if you have questions about making package-manager supported repo for unity. That would indeed help a lot to have.

**Comment by BunyaPineTree** [comment]
That probably would be a good idea. I'm setting things up for a ModelReplacementSDK repo that will hold the current unity project, and eventually turn into an SDK, so package-manager support sounds right up the alley. 

So, I've been fiddling with the jiggleSettings on my miku model, and it looks like creating default cloth and hair settings is quite possible, so I think a merge will be suitable soon, but I have a question on a possible adjustment

From my meagre understanding after reading your and LocalHyena's conversation on the matter, it seems that the jiggle rig no longer supports more than a single rootbone as a result of serializable funniness. 
I noticed this while setting up skirt physics on miku, as I had to manually set the root transform for each of Miku's many skirt bone sequences. 
image
Given that your suggested native support is already modified from your original scripts, it would be most natural for these derivative Jiggle Rigs to set `rootTransform = base.transform` on Awake() as an editor only default behavior.

I was also wondering if it would be possible to package your scripts as an embedded assembly inside of ModelReplacementAPI.dll after noting that your fork has to be cloned recursively, and that it cannot be cloned via zip. It likely isn't necessary for your JiggleBone scripts to be kept in a folder in ModelReplacementAPI, though in researching the matter myself it doesn't seem likely that it can be done in a manner more elegant than the current one.

**Comment by BunyaPineTree** [comment]
Oh, additionally, the TooManyEmotes dev adjusted the namespaces to be public, and a publicized assembly is no longer necessary. I will shortly post a commit that reflects that change, and so long as you have the most recent thunderstore copy of TooManyEmotes.dll, you should be able to compile.

**Comment by naelstrof** [comment]
Okay the DLL is now updated. The other half of the changes will be PR'd to the SDK you've made soon.
I'd recommend deleting the unity package after this PR.

**Pull request merged**
